### ISSUE TITLE
Map symbology does not update when the last remaining inspection is deleted

### ISSUE THREAD

**Issue by mikewilburn** [Esri/data-collection-ios#100]
The tree feature's details which depict the `Condition` of the tree also do not update.
This was one piece of feedback that came out of Sarat's testing of the app (result from test case 4.5).

Steps to repro:
1. Find a tree which only has one inspection record left.
2. Take note of the tree's condition and map symbol color, then delete the inspection.
3. Notice that neither the map symbol updates nor does the `Condition` attribute of the feature get cleared.

**Comment by esreli** [comment]
@mikewilburn A PR has opened that solves this.

**Comment by esreli** [comment]
@mikewilburn This change has been merged into master. Please confirm it has been fixed.

**Comment by mikewilburn** [comment]
Verified on master.
