### ISSUE TITLE
Update for Swift 4.2 and XCode 10

### ISSUE THREAD

**Issue by esreli** [Esri/data-collection-ios#106]
Consider changes:

- https://github.com/apple/swift-evolution/blob/master/proposals/0199-bool-toggle.md
- https://github.com/apple/swift-evolution/blob/master/proposals/0207-containsOnly.md
- https://github.com/apple/swift-evolution/blob/master/proposals/0079-upgrade-self-from-weak-to-strong.md

**Comment by esreli** [comment]
@mikewilburn the app has been updated for Swift 4.2. Would you confirm that it works as expected?

**Comment by esreli** [comment]
Closing this issue. @mikewilburn if you find an issue down the road, feel free to open a new issue.

**Comment by mikewilburn** [comment]
@esreli will do. I've yet to run this version of the app, but I will when I also test with alternate data sources - something I've also been meaning to do.
