### ISSUE TITLE
Reverse geocoder continues to work after logging out

### ISSUE THREAD

**Issue by marastoica** [Esri/data-collection-ios#116]
I tried adding a tree while logged out, and it prompted me to login so the reverse geocoder could get the address. 

After that I logged out and tried adding multiple trees, the reverse geocoder just worked without asking me to login again. Are credentials not fully cleared when user logs out? 

Versions:
Data Collection 1.0 (12)
Runtime SDK 100.3.0 (2102)

**Comment by esreli** [comment]
PR open. https://github.com/Esri/data-collection-ios/pull/119

**Comment by marastoica** [comment]
Shouldn't this be verified by someone before you close it? Or at least a mention of the fact that someone did verify it and the issue was resolved?

**Comment by esreli** [comment]
@marastoica thank you, this was verified in the PR.

**Comment by marastoica** [comment]
So then a link to the PR where it was verified. It's just good practice to show the trail

**Comment by esreli** [comment]
https://github.com/Esri/data-collection-ios/issues/116#issuecomment-425174231
