### ISSUE TITLE
Collect new inspection button still appears even if feature service doesn't participate in 1:M relationship

### ISSUE THREAD

**Issue by mikewilburn** [Esri/data-collection-ios#139]
This came up while testing with a custom web map which contains only a single feature layer - `59ad551de0f042f088ee99ea26321b96`.

Running the app against that web map, you'll notice that identifying a tree point still includes the `+` button to collect a new 1:Many related record, despite the fact that the layer does not participate in a relationship. We should conditionally remove the button if no such relationship exists.

The good news is that we have pretty good error messaging for this case:
![image](https://user-images.githubusercontent.com/25207711/47398163-b6f37c80-d6e7-11e8-9035-d478581626f0.png)

**Comment by esreli** [comment]
@mikewilburn changes have been merged to master. Can you confirm the app works as expected?

**Comment by mikewilburn** [comment]
Verified on master that the `+` button no longer shows up if the identified feature does not participate in a 1-to-Many relationship.

![image](https://user-images.githubusercontent.com/25207711/47581356-01eadb00-d906-11e8-9f5b-700c7fcac7e9.png)
