### ISSUE TITLE
Typo in log in message

### ISSUE THREAD

**Issue by mikewilburn** [Esri/data-collection-ios#140]
When the app loads a web map requiring authentication, the message the user is prompted with has a small typo:
> You must ~login~ log in to access this resource.

![image](https://user-images.githubusercontent.com/25207711/47445196-3b3c1300-d76d-11e8-9a72-28de0b8bf6b5.png)

This web map id should prompt the message: `1300bf23f97f4a2bb6ede795dfab8b72`

**Comment by esreli** [comment]
@mikewilburn this change has been merged into master. Can you verify?

**Comment by mikewilburn** [comment]
Verified on master.

![image](https://user-images.githubusercontent.com/25207711/47582142-6b6be900-d908-11e8-84b2-a3687e8ab06d.png)
