### ISSUE TITLE
Set new initial viewpoint to map view when switching from working online to offline

### ISSUE THREAD

**Issue by mikewilburn** [Esri/data-collection-ios#152]
When a user has an offline map and switches from working online to working offline, it's possible for the offline map to open at an unknown location, leaving the user swimming in a lattice of grey "no data" without any indication of scale or whereabouts.

This is because the present behavior has deterministic rules that attempt to preserve the user's online map extent as best as possible.

If this online map view extent is nowhere near the location of the already-downloaded offline map, this can make it exceptionally difficult to navigate to that area. Even worse, if the user has altogether forgotten where the offline map exists, such behavior could make it altogether impossible to locate the area covered by the offline map.

I propose:
- If the online extent intersects the offline map extent, preserve the extent at the closest scale level to the available offline map
- else set the map view to the centerpoint of the offline map at the coarsest level of detail at which it's available (smallest scale) to provide the most amount of location context

**Comment by mikewilburn** [comment]
@esreli that is just one recommendation as to how we might go about solving this. There are bound to be many other valid solutions. Just didn't want to log a problem without offering a possible solution :)

**Comment by mikewilburn** [comment]
@esreli There are still a few circumstances in which this isn't working.

I'm guessing a bit here, but I think this logic breaks down because the _offlineMap_'s scale can never be smaller than the coarsest LOD at which the offline map is available. So while that intersection evaluation is probably written soundly, when you:
> set _visibleArea_ to _currentExtent_

some of the extent-setting behavior might be getting overridden by the centerpoint of the _currentExtent_ being preserved, but at a sometimes greatly zoomed in scale at which the offline map is well outside of the _visibleArea_. This means you're dropped into this lattice of grey and would only be able to navigate to the offline map if you knew precisely in which direction to pan and by how much.

I can show you more of this in person, because that's pretty hard to decipher in writing.

**Comment by mikewilburn** [comment]
By contrast, it looks like the .NET app permits zooming out beyond the initial extent that was used to capture the offline map:
![image](https://user-images.githubusercontent.com/25207711/48233920-0e424f80-e36c-11e8-85c4-e8927d12e604.png)

**Comment by mikewilburn** [comment]
If I'm understanding correctly here, I think just **a)** would be sufficient. I think it would be fine to allow the user to zoom out as the .NET version of the app does.

**Comment by esreli** [comment]
Sounds good.

**Comment by esreli** [comment]
With this technique I will note that for any map that is already downloaded, the scale will remain at what is was specified at the time of the download.

So, this fix will only fix all maps moving forward and won't account for any maps that have already downloaded.

**Comment by esreli** [comment]
@mikewilburn the change has been implemented. Specifically, the offline map's minScale is set with the same value as the online map's.

In order test you will have to use a new downloaded map. Any existing downloaded maps min/max scale values will persist.

**Comment by mikewilburn** [comment]
This looks good to me @esreli.

From testing a bit, I was able to conclude the following two behaviors:
- If the extent of the online map is enough to intersect the offline map when switching to offline mode, the extent will be preserved
- If the extent of the online map is _not_ enough to intersect the offline map when switching to offline mode, the extent will be set to that of the offline map.

_Example when toggling to offline map from online mode:_
![image](https://user-images.githubusercontent.com/25207711/49121712-4f8c9780-f266-11e8-98d9-f4f6a4abd1ae.png)
