### ISSUE TITLE
Introduce a two project environment approach.

### ISSUE THREAD

**Issue by esreli** [Esri/data-collection-ios#161]
These two environments should be Development and Production, allowing us to develop the app on a web map without consequence of adding/updating/deleting good data.

**Comment by esreli** [comment]
@mikewilburn can you provide me with the two web map item ids associated with `Development` and `Production`?

**Comment by mikewilburn** [comment]
This seemed like a quick enough thing to tick off so I went ahead and did it.

`Development`: e1aa3973d50a456f998406a7c4dfd804
`Production`: 16f1b8ba37b44dc3884afc8d5f454dd2

**Comment by esreli** [comment]
Thank you.

**Comment by esreli** [comment]
This is no longer a requirement of the app. Closing.
