### ISSUE TITLE
Resulting attachment size differs from selected PREFERRED SIZE

### ISSUE THREAD

**Issue by mikewilburn** [Esri/data-collection-ios#174]
When attaching a new image, the `PREFERRED SIZE` menu permits downsampling the image size to save file space and allow for faster sync times:

![image](https://user-images.githubusercontent.com/25207711/55353151-6db60e80-5477-11e9-8de8-eb9a7130e72e.png)

However, this size appears to be getting ignored and instead honoring 3x scale factor.

For instance, when specifying a size of `Medium (480x640)`, the resulting image size being uploaded is actually `1440x1920`.

**Comment by mikewilburn** [comment]
In the latest version of Collector for iOS, I confirmed that their selected sizes are consistent with what's listed in the iOS API ref [here](https://developers.arcgis.com/ios/latest/api-reference/_a_g_s_enumerations_8h.html#acbeb74606c1a71ec892616b77953fc92).

A size 'Large' does upload an image of size of `960x1280`, however they've removed these discrete size definitions from the corresponding settings menu:
![image](https://user-images.githubusercontent.com/25207711/55353355-ee750a80-5477-11e9-97c5-909ee3765038.png)

**Comment by esreli** [comment]
The SDK downsamples images respecting the main screen's scale. There are a few options available to us to better express to our users what is happening under the hood of the SDK:

1. Specify points in the preferred size options table.
2. Write a multiplier for the preferred size options relative to screen scale, outputting in the preferred size options table the actual down-sample size in pixels.
3. Down-sample the image ourself. (This should be considered last.)

Thoughts? @mikewilburn

**Comment by esreli** [comment]
Adding label `Type - Enhancement` and removing `Type - Bug` because this behavior is as designed. This does not deny the need to address this concern and merits an examination of how this can be more easily understood.

**Comment by mikewilburn** [comment]
My preference would be for number **2** above.

I think the attached file size should be consistent with what's listed in the preferred size options table and the API documentation. This would achieve that.

As well, I don't think an end user should have to consider a scale factor when attaching images. It should be handled behind the scenes, either by the app's logic, or by the API itself (more ideal).

**Comment by esreli** [comment]
This changes has been implemented. Please confirm this issue can be closed.

**Comment by mikewilburn** [comment]
Changes confirmed in branch `v.next`.

On an iPhone X (which has a 3x scale factor), the new preferred sizes are:
![image](https://user-images.githubusercontent.com/25207711/55595808-6488a400-56fa-11e9-8818-237bdbb53b87.png)
