### ISSUE TITLE
Removing a feature attachment still persists it in current app session

### ISSUE THREAD

**Issue by mikewilburn** [Esri/data-collection-ios#180]
**In the Runtime app:**

1. identify a feature that has some number of attachments on it
2. do not close the app

**In a web browser:**

3. using the AGOL map viewer, view the same web map
4. edit the feature in by removing one of the attachments

**Back in the Runtime app:**

5. in the same app session as before, re-identify the feature
6. browse to the feature's attachments and notice that the deleted attachment still exists

**Note:** closing and reopening the app restores the correct view of the attachment; the deleted attachment will not appear.

**Comment by esreli** [comment]
This is a design choice made by Runtime. As such, I'm closing this issue.
