### ISSUE TITLE
Possible regression? Closing the app gives the appearance of logging out the user

### ISSUE THREAD

**Issue by mikewilburn** [Esri/data-collection-ios#186]
After **1)** logging into the app, **2)** close the app from the app tray. **3)** Re-launch the app and visit the app mode drawer and notice that the profile icon has changed to 'Log in'. Moreover, **4)** tapping the 'Log in' icon at this point appears to trigger an _actual_ log out.

![image](https://user-images.githubusercontent.com/25207711/56230574-6d9a3f00-6031-11e9-8646-2700576bec94.png) ![image](https://user-images.githubusercontent.com/25207711/56230592-79860100-6031-11e9-921b-179b540d5c74.png) ![image](https://user-images.githubusercontent.com/25207711/56230603-7d198800-6031-11e9-833e-ba008f868fa2.png) ![image](https://user-images.githubusercontent.com/25207711/56230607-80ad0f00-6031-11e9-8048-5396fae66639.png)

**Comment by mikewilburn** [comment]
I should mention that **steps 1-3** above don't log the user out, but rather give that appearance.
Testing with a private web map, access to and interaction with that web map remains through **step 3.**
It is not until **step 4** and tapping the 'Log in' control that access to the web map is lost.

**Comment by esreli** [comment]
This bug is fixed. Closing.
