### ISSUE TITLE
App doesn't validate attachment file name

### ISSUE THREAD

**Issue by codergrl** [Esri/data-collection-ios#188]
When renaming a new attachment, the app should validate so the user cannot enter invalid characters like spaces, backslashes, etc. Currently the app allows the user to enter invalid characters, and then it fails to save the attachment throwing a null pointer exception. 

Here's the regex used in the dotnet app to validate: `^[^\\\/:*?""<>|\s]+$`

**Comment by nCastle1** [comment]
It looks like the editing is a separate issue (affects master as well) so I'll open a separate issue.

**Comment by mhdostal** [comment]
> I tried the branch with the fix. I noticed that it still allowed me to enter `]`, but it was saved as `_`.

It's fine with me iff there are characters that the system can handle but get translated; it just can't fail to save the attachment.

**Comment by mhdostal** [comment]
Verified fixed in the v1.1.2 release.
