### ISSUE TITLE
Typo in root README

### ISSUE THREAD

**Issue by yo1995** [Esri/data-collection-ios#268]
![image](https://user-images.githubusercontent.com/9660181/100671456-5d71c900-3315-11eb-8467-c6715c50aaf0.png)

In `Configure app secrets` section there is a typo. See above.

**Comment by esreli** [comment]
Thanks for catching this typo, @yo1995. We've fixed the typo and it's staged in the next patch release, [`v.next-1.2.3`](https://github.com/Esri/data-collection-ios/blob/v.next-1.2.3/README.md#3-configure-app-secrets)
