### ISSUE TITLE
Consider: Use UIGraphicsImageRenderer

### ISSUE THREAD

**Issue by esreli** [Esri/data-collection-ios#62]
in `data-collection/data-collection/Extensions/UIKit/UIImage+Extensions.swift`

**Comment by esreli** [comment]
@philium thank you for your contribution in https://github.com/Esri/data-collection-ios/pull/132

Would you also be interested in converting the other `UIImage` render extension?
`func circularThumbnail(ofSize diameter: CGFloat, stroke: (color: UIColor, weight: CGFloat)?) -> UIImage?`

**Comment by philium** [comment]
Sure thing.

**Comment by esreli** [comment]
Thank you for your help @philium. Closing this issue.

**Comment by esreli** [comment]
https://github.com/Esri/data-collection-ios/pull/135
